### ISSUE TITLE
Can't find 'test.wav' file

### ISSUE THREAD

**Issue by FoxerLee** [jsjtxietian/PersonalArtCompany#1]
After running `yarn start`, an error was found:

```
./src/App.js
Module not found: Can't resolve './Music/test.wav' in '/Users/liyuan/Documents/Interesting Code collection/PersonalArtCompany/src'
```

Looks like './Music/test.wav' was missing

**Comment by jsjtxietian** [comment]
the project is under development  & the music source is much too big to upload ;
